# Generated by Django 6.0.8 on 2026-09-26 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('budgets', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                (
                    'type',
                    models.CharField(
                        choices=[('period', 'Period'), ('project', 'Project')], max_length=10
                    ),
                ),
                (
                    'period_start',
                    models.DateField(
                        blank=True,
                        help_text='Required for period budgets; must be blank for project budgets.',
                        null=True,
                    ),
                ),
                (
                    'period_end',
                    models.DateField(
                        blank=True,
                        help_text='Required for period budgets; must be blank for project budgets.',
                        null=True,
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        help_text='Inactive budgets are hidden from the budgets list but preserved for historical reporting. Use instead of hard-deleting.',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'household',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='budgets',
                        to='users.household',
                    ),
                ),
            ],
            options={
                'db_table': 'budgets',
                'ordering': ['-period_start', 'name'],
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ('period_end__isnull', False),
                                ('period_start__isnull', False),
                                ('period_start__lte', models.F('period_end')),
                                ('type', 'period'),
                            ),
                            models.Q(
                                ('period_end__isnull', True),
                                ('period_start__isnull', True),
                                ('type', 'project'),
                            ),
                            _connector='OR',
                        ),
                        name='budget_period_type_matches_dates',
                    )
                ],
                'unique_together': {('household', 'name')},
            },
        ),
    ]
