# Generated by Django 6.0.8 on 2026-09-22 21:18

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('budgets', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('spending', 'Spending'),
                            ('earning', 'Earning'),
                            ('project', 'Project'),
                        ],
                        max_length=10,
                    ),
                ),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        help_text='Inactive budgets are hidden from pickers. Use instead of hard-deleting.',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'household',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='budgets',
                        to='users.household',
                    ),
                ),
            ],
            options={
                'db_table': 'budgets',
                'ordering': ['-created_at'],
                'unique_together': {('household', 'name', 'type')},
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'planned_amount',
                    models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
                ),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'budget',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lines',
                        to='budgets.budget',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='budget_lines',
                        to='budgets.category',
                    ),
                ),
            ],
            options={
                'db_table': 'budget_lines',
                'ordering': ['category__type', 'category__name'],
                'unique_together': {('budget', 'category')},
            },
        ),
    ]
