# Generated by Django 6.0.8 on 2026-10-05 15:59

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('budgets', '0002_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('planned_amount', models.IntegerField(default=0)),
                (
                    'actual_amount',
                    models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
                ),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'budget',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lines',
                        to='budgets.budget',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='budget_lines',
                        to='budgets.category',
                    ),
                ),
            ],
            options={
                'db_table': 'budget_lines',
                'ordering': ['category__type', 'category__name'],
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(('planned_amount__gte', 0)),
                        name='budget_line_planned_amount_non_negative',
                    )
                ],
                'unique_together': {('budget', 'category')},
            },
        ),
    ]
