# Generated by Django 6.0.8 on 2026-10-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('budgets', '0003_budgetline'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.CheckConstraint(
                condition=models.Q(('planned_amount__gte', 0)),
                name='budget_line_planned_amount_non_negative',
            ),
        ),
    ]
