# Generated by Django 6.0.8 on 2026-10-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('budgets', '0003_budgetline'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
