# Generated by Django 6.0.8 on 2026-08-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='handler_key',
            field=models.CharField(
                choices=[
                    ('sofi-savings', 'SoFi Savings'),
                    ('sofi-checking', 'SoFi Checking'),
                    ('co-checking', '360 Checking'),
                    ('co-savings', '360 Performance Savings'),
                    ('co-quicksilver', 'Quicksilver Credit Card'),
                    ('wf-checking', 'Checking'),
                    ('wf-savings', 'Savings'),
                    ('chase', 'Chase Card'),
                    ('discover', 'Discover Card'),
                    ('amex-delta', 'Delta SkyMiles Card'),
                    ('citi-costco', 'Costco Anywhere Visa Card'),
                ],
                max_length=255,
                unique=True,
            ),
        ),
    ]
