# Generated by Django 6.0.2 on 2026-02-17 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('handler_key', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'account_types',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='banks/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'banks',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='users.household')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='transactions.accounttype')),
            ],
            options={
                'db_table': 'accounts',
                'unique_together': {('household', 'name')},
            },
        ),
        migrations.AddField(
            model_name='accounttype',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_types', to='transactions.bank'),
        ),
        migrations.AlterUniqueTogether(
            name='accounttype',
            unique_together={('bank', 'name')},
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('concept', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_labels', models.TextField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transactions.account')),
            ],
            options={
                'db_table': 'transactions',
                'indexes': [models.Index(fields=['date'], name='idx_transactions_date'), models.Index(fields=['label'], name='idx_transactions_label'), models.Index(fields=['category'], name='idx_transactions_category')],
            },
        ),
    ]
