# Generated by Django 6.0.2 on 2026-03-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0003_seed_account_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(
                choices=[('import', 'Import'), ('manual', 'Manual')],
                default='import',
                max_length=10,
            ),
        ),
    ]
