# Generated by Django 6.0.2 on 2026-02-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_seed_account_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='handler_key',
            field=models.CharField(choices=[('sofi-savings', 'SoFi Savings'), ('sofi-checking', 'SoFi Checking'), ('co-checking', '360 Checking'), ('co-savings', '360 Performance Savings'), ('co-quicksilver', 'Quicksilver Credit Card'), ('wf-checking', 'Checking'), ('wf-savings', 'Savings'), ('chase', 'Chase Card'), ('discover', 'Discover Card'), ('amex-delta', 'Delta SkyMiles Card')], max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
