# Generated by Django 6.0.2 on 2026-03-20 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0004_transaction_source'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                (
                    'color',
                    models.CharField(
                        default='#6B7280',
                        help_text='Hex colour code, e.g. "#FF5733".  Used for UI display only.',
                        max_length=7,
                    ),
                ),
                (
                    'category',
                    models.CharField(
                        blank=True,
                        default='',
                        help_text='Optional grouping for related labels (e.g. "Food", "Bills").',
                        max_length=100,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'household',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='labels',
                        to='users.household',
                    ),
                ),
            ],
            options={
                'db_table': 'labels',
                'ordering': ['category', 'name'],
                'unique_together': {('household', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='label',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='transactions',
                to='transactions.label',
            ),
        ),
    ]
