# Generated by Django 6.0.3 on 2026-03-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0005_label_alter_transaction_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='exclude_from_summary',
            field=models.BooleanField(
                default=False,
                help_text='When True this transaction is omitted from summary aggregations. Use for transfers, loan proceeds, or any amount that would otherwise distort spending/earnings totals.',
            ),
        ),
    ]
