# Generated by Django 6.0.3 on 2026-04-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0006_transaction_exclude_from_summary'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'date', 'id'], name='idx_transactions_cursor'),
        ),
    ]
