# Generated by Django 6.0.8 on 2026-09-20 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('budgets', '0001_initial'),
        ('transactions', '0008_account_fk_to_banking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['category__name', 'name']},
        ),
        migrations.RunSQL(
            sql="UPDATE labels SET category = NULL WHERE category = ''",
            reverse_sql="UPDATE labels SET category = '' WHERE category IS NULL",
        ),
        migrations.AlterField(
            model_name='label',
            name='category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='labels',
                to='budgets.category',
            ),
        ),
    ]
