# Generated by Django 6.0.8 on 2026-10-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0009_alter_label_options_alter_label_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True,
                help_text='Bumped on every save, not just import — reassigning label/category, toggling exclude_from_summary, or editing amount all count. Lets callers that cache a computation over a set of transactions (e.g. budget actuals) detect staleness by comparing against the latest updated_at in that set, without needing to redo the computation to find out whether anything changed.',
            ),
        ),
    ]
