# Generated by Django 6.0.8 on 2026-10-05 16:47, then hand-edited to split
# into add-nullable / backfill / make-non-null steps — see backfill_updated_at
# below for why.

from django.db import migrations, models


def backfill_updated_at(apps, schema_editor):
    """Seeds updated_at from imported_at for every pre-existing row.

    A straight single-step AddField with auto_now=True would still apply —
    MySQL lets Django add a NOT NULL column to a populated table by
    supplying a one-off default — but that default is the literal instant
    makemigrations happened to run, frozen into this file, not anything
    derived from each row's own history. Every pre-existing transaction
    would end up with the exact same updated_at, often earlier than its
    own imported_at if this migration is applied well after it was
    written. Backfilling from imported_at is the closest honest answer:
    "as far as we know, this row hasn't changed since it was imported."
    """
    Transaction = apps.get_model('transactions', 'Transaction')
    Transaction.objects.update(updated_at=models.F('imported_at'))


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0009_alter_label_options_alter_label_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(backfill_updated_at, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True,
                help_text=(
                    'Bumped on every save, not just import — reassigning '
                    'label/category, toggling exclude_from_summary, or editing '
                    'amount all count. Lets callers that cache a computation '
                    'over a set of transactions (e.g. budget actuals) detect '
                    'staleness by comparing against the latest updated_at in '
                    'that set, without needing to redo the computation to find '
                    'out whether anything changed.'
                ),
            ),
        ),
    ]
